sudo: required
language: scala
scala:
- 2.11.6
services:
- docker
install: true
before_install:
- "./tools/travis/setup.sh"
script:
- "./tools/travis/build.sh"
dd:
- openssl aes-256-cbc -K $encrypted_c785b698887e_key -iv $encrypted_c785b698887e_iv
  -in secret_test.txt.enc -out secret_test.txt -d
